name: country_app
description: This is an app to show you different countries and their description

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # State Management
  stacked: ^3.0.0
  stacked_services: ^0.9.8
  flutter_hooks: ^0.18.2+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^2.3.2
  stacked_generator: ^0.8.0+1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
