name: country_app
description: This is an app to show you different countries and their description

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # State Management
  stacked: ^3.0.0
  stacked_services: ^0.9.8
  flutter_hooks: ^0.18.2+1

  # Utilities
  faker: ^2.0.0
  uuid: ^3.0.6
  http: ^0.13.5

  # Data Models
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # UI Components
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  font_awesome_flutter: ^ 10.2.1
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^2.3.2
  stacked_generator: ^0.8.0+1

  # data models
  freezed: ^2.2.1
  json_serializable: ^6.5.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/